# Generated by Django 3.2.6 on 2022-04-27 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Clang_attendance',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(101)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='Clang_marks_1',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(101)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='Clang_marks_2',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(101)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='Clang_marks_3',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(101)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='ITW_attendance',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(101)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='ITW_marks_1',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(101)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='ITW_marks_2',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(101)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='ITW_marks_3',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(101)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='IoT_attendance',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(101)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='IoT_marks_1',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(101)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='IoT_marks_2',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(101)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='IoT_marks_3',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(101)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='Stats_attendance',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(101)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='Stats_marks_1',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(101)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='Stats_marks_2',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(101)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='Stats_marks_3',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(101)]),
        ),
    ]
